# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2e06eb496ad115de2bdca73da4018c70f3c629f83c856035a21b58724ee1fa1c0b0c29eb045a7ebf31173a13f8d49725ded43f68df12691f899b67819c30dac

test:
  secret_key_base: 305fa2dd78687328d2a549978e7016d824b307e3e2c546a59a3d86e3da2155824332fe28606b86b93ef08d4ddb2f699c1139acd4aba82feef72efba0169de94f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
